/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Bachklamk (https://sketchfab.com/Bachklamk)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/cad1fc9ada864e06ab69a37705656392
title: TRON-ish low-poly drone
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.9, -0.6, -0.14]}>
          <mesh
            geometry={nodes.mesh_0.geometry}
            material={materials["Material.067"]}
          />
          <mesh
            geometry={nodes.mesh_1.geometry}
            material={materials["Material.068"]}
          />
          <mesh
            geometry={nodes.mesh_2.geometry}
            material={materials["Material.069"]}
          />
          <mesh
            geometry={nodes.mesh_3.geometry}
            material={materials["Material.070"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
